#!/bin/bash
# =============================================================================
# user/mkefs.sh -- Genera el filesystem embebido (efsfiles.c) del kernel
# -----------------------------------------------------------------------------
# Rol dentro de EDOS:
#   Toma como argumentos una lista de archivos (programas .bin + archivos de
#   datos como README) y genera en la raíz del proyecto el archivo
#   `efsfiles.c`, que el kernel linkea para tener sus "archivos" en memoria.
#
# Cómo lo usa el Makefile:
#   ./mkefs.sh init README
#
# Salida:
#   1) Un array `unsigned char <name>_bin[] = {...}` (o `<name>[]` para datos).
#   2) Una constante `<name>_bin_len` / `<name>_len` (marcada como `const`).
#   3) La tabla `efs_files_table[] = { {"name", TYPE, ptr, len}, ..., {0,0,0,0} }`.
#
# ⚠ Cuidado:
#   - Si un archivo tiene .bin al lado (por ej. init.bin generado por objcopy),
#     se asume que es PROGRAMA. Si no, se asume archivo de datos.
#   - `xxd -i` es el que hace la magia de generar el array C desde bytes.
# =============================================================================

tmp="efsfiles.tmp"                                  # archivo temporal.

# ---- Escribimos el header ---------------------------------------------------
echo "// Generated by mkefs.sh utility" > "$tmp"
echo -e '#include' \"efs.h\" '\n' >> "$tmp"

# ---- Por cada archivo, generar su array C con xxd ---------------------------
for f in "$@"
do
    echo generating  "$f" ...
    if [ -e "$f.bin" ]                             # ¿Es un programa (tiene .bin)?
    then
        xxd -i "$f.bin" >> "$tmp"                  # Sí → xxd sobre el .bin.
    else
        xxd -i "$f" >> "$tmp"                      # No → xxd sobre el archivo.
    fi
    echo '' >> "$tmp"
done

# ---- Convertir "unsigned int" a "const unsigned int" (para .rodata) ---------
sed 's/unsigned int/const unsigned int/g' "$tmp" > efsfiles.c
rm "$tmp"

# ---- Escribir la tabla efs_files_table[] ------------------------------------
echo -e 'struct file efs_files_table[] = {' >> efsfiles.c
for f in "$@"
do
    if [ -e "$f.bin" ]
    then
        t="EFS_FILE_PROGRAM"                       # tipo = programa ejecutable
        echo -e '\t'{\""$f"\", "$t", "$f"_bin, "$f"_bin_len}, >> efsfiles.c
    else
        t="EFS_FILE_DATA"                          # tipo = datos
        echo -e '\t'{\""$f"\", "$t", "$f", "$f"_len}, >> efsfiles.c
    fi
done

# ---- Fin de la tabla + centinela {0,0,0,0} ----------------------------------
echo -e '\t{0, 0, 0, 0}\n};' >> efsfiles.c

# ---- Mover efsfiles.c a la raíz del proyecto (donde vive el kernel) ---------
echo "Moving efsfiles.c to kernel directory..."
mv efsfiles.c ..
