#!/bin/bash
tmp="efsfiles.tmp"
echo "// Generated by mkefs.sh utility" > "$tmp"
echo -e '#include' \"efs.h\" '\n' >> "$tmp"

# generate C data for programs (.bin files) and data files using xxd
for f in "$@"
do
    echo generating  "$f" ...
    if [ -e "$f.bin" ]
    then
        xxd -i "$f.bin" >> "$tmp"
    else
        xxd -i "$f" >> "$tmp"
    fi
    echo '' >> "$tmp"
done

# replace length variable declarations for constants
sed 's/unsigned int/const unsigned int/g' "$tmp" > efsfiles.c
rm "$tmp"
echo -e 'struct file efs_files_table[] = {' >> efsfiles.c

# Initialize files table
for f in "$@"
do
    if [ -e "$f.bin" ]
    then
        t="EFS_FILE_PROGRAM"
        echo -e '\t'{\""$f"\", "$t", "$f"_bin, "$f"_bin_len}, >> efsfiles.c
    else
        t="EFS_FILE_DATA"
        echo -e '\t'{\""$f"\", "$t", "$f", "$f"_len}, >> efsfiles.c
    fi
done

# close the files table
echo -e '\t{0, 0, 0, 0}\n};' >> efsfiles.c

echo "Moving efsfiles.c to kernel directory..."
mv efsfiles.c ..
